version: "3.7"
services:
    backend_dev:
        build:
            context: .
        ports:
            - 5002:3000
        volumes:
            - ".:/app"
            - "/app/node_modules"
        entrypoint : [ "npm","run", "start" ]
        container_name: reddit_ts_frontend
        image: reddit_ts_frontend:dev
        