version: "3.7"
services:
    frontend:
        build:
            context: .
        ports:
            - 5002:3000
        volumes:
            - ".:/app"
            - "/app/node_modules"
        entrypoint : [ "npm","run", "dev" ]
        container_name: reddit_trending_next
        image: reddit_trending_next:dev
        